name: updateVersion

on:
  pull_request:
    branches: [ master ]
    # types: [closed]

jobs:
  updateVersionJob:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # outputs:
      # output1: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: chmod & update git branch
      run: |
        chmod 700 *.sh
    - name: ini git
      run: |
        echo "-------------"
        git fetch
        # TODO cr√©er les branches distante en local pour que getLastGitBranch.sh fonctione
        git switch 2.9
        echo "-------------"
        lastBranch=$(./getLastGitBranch.sh)
        echo $lastBranch
        echo "-------------"
        git switch $lastBranch
        echo "-------------"
        # git branch
        # echo "-------------"
        # git checkout master
        # ls
        # git checkout refs/heads/$(./getLastGitBranch.sh)
        # git pull
    - name: updateVersion.sh
      run: ./updateVersion.sh
    - name: commit version.md
      run: |
        if [[ `git status --untracked-files=no --porcelain docs/` != "\n" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.md
          git commit -m "Auto version.md update"
          git push
        fi
